name: Docker Image Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v3

      - name: Build and push image
        run: |
          docker build -t $AWS_ECR_REPOSITORY_URI .
          docker push $AWS_ECR_REPOSITORY_URI
        env:
          AWS_ECR_REPOSITORY_URI: your-ecr-repo-uri
