name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }} with pnpm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        package-manager: pnpm

    - name: Cache pnpm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-cache-

    - name: Install dependencies
      run: pnpm install

    - name: Build with webpack
      run: pnpm run build
